[[redirects]]
  from = "/*"
  to = "/.next/server/app/:splat"
  status = 200

[build]
  base = "client"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
